stages:
- stage: RePlan
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: 
  - AutoApply
  - Apply
  condition: and(not(canceled()), not(and(eq(dependencies.Apply.result, 'Skipped')), eq(dependencies.AutoApply.result, 'Skipped')), eq(dependencies.Plan.outputs['Plan.Variable.ShouldRun'], 'true'))
  jobs:
  
  # Delay Job
  #- template: ../Jobs/delay.yml

  # Plan Jobs
  - template: ../Jobs/replan.yml

  # Plan Evaluation Job
  - template: ../Jobs/reevaluate.yml